mqtt:
    broker: 10.0.0.210
    port: 1883
    client_id: kamstrup
    topic_prefix: kamstrup
    qos: 0
    retain: False
    authentication: False
    user: user1
    password: changeit
    tls_enabled: False
    # tls_ca_cert: 
    # tls_cert:
    # tls_key:
    # tls_key_password:
    # tls_insecure: True
    # tls_version: ssl.PROTOCOL_TLSv1_2
serial_device:
    com_port: /dev/ttyKamstrup
kamstrup:
    parameters:
    - energy
    - volume
    - temp1
    - temp2
    poll_interval: 28
